### ISSUE TITLE
Nothing has been arranged yet

### ISSUE THREAD

**Issue by marijn** [DDDNL/ov-chipcard-strikes-back#1]
- [x] Update the Meetup page
- [x] Survey participants (I'd like to give [typeform.com](http://typeform.com) a shot)
  1. Where you at the previous meetup?
  2. Do you have an OV-Chipcard
  3. What is your primary programming language?
  4. What programming language are you most interested in?
  5. Estimate your own DDD skill level
- [x] Announce Survey
- [x] Announce logistics and timeline on meetup
- [x] Setup infrastructure
  - [x] Messaging 
  - [x] Self testing setup in different languages
- [ ] Assign teams
  - [ ] Print name tags
  - [ ] Bring coloured stickers
- [x] Prepare introduction
  - [x] Introduce rule #unrelated
- [x] Enforce timeboxes
  - [x] Buy egg timer
- [x] Write user stories
  - [x] Pay for travel by Check-In/Check-Out
  - [x] Review my travel history
  - [x] Claim back money for unfair charges
- [x] Make a decent time plan
- [x] Agree with venue on timing of food and drinks
- [x] Ensure table setup at venue 
- [ ] Find a funny name
- [ ] Setup Github
  - [ ] Milestones per iteration
- [x] Bring supplies
  - [x] Markers
  - [x] Stickies
  - [x] Infinite paper

**Comment by lisachenko** [comment]
Guys, I wish you good luck! ) :+1:

**Comment by marijn** [comment]
Thans Alex :-)
